# LOCAL

version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: juan
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - mynetwork

 #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx:/var/log/nginx/
    networks:
      - mynetwork

  #Mysl Service
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_USER:
    ports:
      - 33060:3306
    networks:
      - mynetwork

  #Redis
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
